#!/usr/bin/env bash
#
# Builds signed release binaries for Google Play.
#
# The first run creates an upload key and a keystore.properties for you, so there
# is no manual signing setup. Every run after that just reuses them.
#
#   ./build-release.sh              signed AAB (for Play) + signed APK (to sideload)
#   ./build-release.sh --aab-only   just the AAB
#   ./build-release.sh --apk-only   just the APK
#
# Override the defaults with environment variables if you want:
#   KEYSTORE_FILE=my.jks KEY_ALIAS=upload KEYSTORE_PASSWORD=... ./build-release.sh
#
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

WANT_AAB=1; WANT_APK=1
while [ $# -gt 0 ]; do
  case "$1" in
    --aab-only) WANT_APK=0 ;;
    --apk-only) WANT_AAB=0 ;;
    -h|--help)  sed -n '3,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

# shellcheck source=build-lib.sh
. ./build-lib.sh
load_build_conf "$PWD"

KEYSTORE="${KEYSTORE_FILE:-upload.jks}"
ALIAS="${KEY_ALIAS:-upload}"
DNAME="${KEY_DNAME:-CN=App, O=App, C=US}"
SLUG="${APP_SLUG:-app}"
PROPS="keystore.properties"

cyan() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }
info() { printf '    \033[90m%s\033[0m\n' "$1"; }
warn() { printf '    \033[33m! %s\033[0m\n' "$1"; }
die()  { printf '\n\033[31m%s\033[0m\n' "$1" >&2; exit 1; }
# native_path, posix_path and find_keytool come from build-lib.sh

random_password() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -base64 24 | tr -d '\n/+=' | cut -c1-24
  elif [ -r /dev/urandom ];              then head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | cut -c1-24
  else date +%s%N | sha256sum | cut -c1-24
  fi
}

# ------------------------------------------------------------ signing setup ---
if [ ! -f "$PROPS" ]; then
  cyan "Setting up signing (first run only)"

  KEYTOOL_BIN="$(find_keytool)" || die \
"keytool not found. It ships with the JDK.
    Point at it directly in build.local.conf, e.g.
      KEYTOOL=\"T:/Program Files/Android/Android Studio/jbr/bin/keytool.exe\"
    or set JAVA_HOME to the JDK root."
  info "keytool $KEYTOOL_BIN"

  if [ -f "$KEYSTORE" ]; then
    # keystore exists but we have no properties file: we need the password
    info "Found $KEYSTORE but no $PROPS."
    if [ -n "${KEYSTORE_PASSWORD:-}" ]; then
      PASS="$KEYSTORE_PASSWORD"
    else
      printf '    Keystore password: '
      read -r -s PASS
      printf '\n'
    fi
    [ -n "$PASS" ] || die "No password given."
  else
    PASS="${KEYSTORE_PASSWORD:-$(random_password)}"
    info "Creating upload key $KEYSTORE (valid ~27 years)"
    "$KEYTOOL_BIN" -genkeypair \
      -keystore "$KEYSTORE" -alias "$ALIAS" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -storepass "$PASS" -keypass "$PASS" \
      -dname "$DNAME" >/dev/null
    chmod 600 "$KEYSTORE" 2>/dev/null || true
    info "key created"
  fi

  umask 077
  cat > "$PROPS" <<PROPFILE
# Generated by build-release.sh. Gitignored - never commit this.
storeFile=$(native_path "$PWD/$KEYSTORE")
storePassword=$PASS
keyAlias=$ALIAS
keyPassword=$PASS
PROPFILE
  info "wrote $PROPS"

  printf '\n\033[33m'
  cat <<TXT
    ---------------------------------------------------------------
    BACK UP $KEYSTORE AND $PROPS, SOMEWHERE SAFE
    AND OFF THIS MACHINE.

    Google Play ties your listing to this key. Lose it and you can
    never publish an update to the same app - you'd have to start
    a new listing and every install would be orphaned.
    ---------------------------------------------------------------
TXT
  printf '\033[0m'
else
  info "Using existing $PROPS"
fi

# ------------------------------------------------------------------- build ---
[ "$WANT_AAB" = "1" ] && { cyan "Building signed AAB for Play"; ./build-apk.sh --bundle; }
[ "$WANT_APK" = "1" ] && { cyan "Building signed APK";          ./build-apk.sh --release; }

cyan "Release build finished"
[ "$WANT_AAB" = "1" ] && printf '    \033[32m%s\033[0m  upload this to Play\n'     "$SLUG-release.aab"
[ "$WANT_APK" = "1" ] && printf '    \033[32m%s\033[0m  install this on a phone\n' "$SLUG-release.apk"

cat <<TXT

    Play checklist is in BUILD.md. The short version:
      - privacy policy URL: ${PRIVACY_URL:-<set PRIVACY_URL in build.conf>}
      - Data safety: answer "no data collected" throughout
      - store listing must say pretend / entertainment, not a real scanner
TXT
