#!/usr/bin/env bash
#
# Builds signed release binaries for Google Play.
#
# The first run creates an upload key and a keystore.properties for you, so there
# is no manual signing setup. Every run after that just reuses them.
#
#   ./build-release.sh              signed AAB (for Play) + signed APK (to sideload)
#   ./build-release.sh --aab-only   just the AAB
#   ./build-release.sh --apk-only   just the APK
#
# Override the defaults with environment variables if you want:
#   KEYSTORE_FILE=my.jks KEY_ALIAS=upload KEYSTORE_PASSWORD=... ./build-release.sh
#
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

WANT_AAB=1; WANT_APK=1
while [ $# -gt 0 ]; do
  case "$1" in
    --aab-only) WANT_APK=0 ;;
    --apk-only) WANT_AAB=0 ;;
    -h|--help)  sed -n '3,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

# Settings come from build.conf beside this script; environment variables win.
_keep_ks="${KEYSTORE_FILE:-}"; _keep_alias="${KEY_ALIAS:-}"; _keep_dname="${KEY_DNAME:-}"
# shellcheck source=build.conf
[ -f build.conf ] && . ./build.conf
[ -n "$_keep_ks" ]    && KEYSTORE_FILE="$_keep_ks"
[ -n "$_keep_alias" ] && KEY_ALIAS="$_keep_alias"
[ -n "$_keep_dname" ] && KEY_DNAME="$_keep_dname"

KEYSTORE="${KEYSTORE_FILE:-upload.jks}"
ALIAS="${KEY_ALIAS:-upload}"
DNAME="${KEY_DNAME:-CN=App, O=App, C=US}"
SLUG="${APP_SLUG:-app}"
PROPS="keystore.properties"

cyan() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }
info() { printf '    \033[90m%s\033[0m\n' "$1"; }
warn() { printf '    \033[33m! %s\033[0m\n' "$1"; }
die()  { printf '\n\033[31m%s\033[0m\n' "$1" >&2; exit 1; }

# Git Bash speaks /c/... but Java reads this path out of a .properties file
native_path() {
  case "$(uname -s 2>/dev/null || echo x)" in
    MINGW*|MSYS*|CYGWIN*)
      command -v cygpath >/dev/null 2>&1 && cygpath -m "$1" || printf '%s' "$1" ;;
    *) printf '%s' "$1" ;;
  esac
}

random_password() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -base64 24 | tr -d '\n/+=' | cut -c1-24
  elif [ -r /dev/urandom ];              then head -c 32 /dev/urandom | base64 | tr -d '\n/+=' | cut -c1-24
  else date +%s%N | sha256sum | cut -c1-24
  fi
}

find_keytool() {
  if [ -n "${JAVA_HOME:-}" ]; then
    for k in "$JAVA_HOME/bin/keytool" "$JAVA_HOME/bin/keytool.exe"; do
      [ -f "$k" ] && { printf '%s' "$k"; return 0; }
    done
  fi
  command -v keytool >/dev/null 2>&1 && { printf 'keytool'; return 0; }
  # last resort: wherever Android Studio put its bundled JDK
  for base in "${ProgramFiles:-}/Android/Android Studio" "$HOME/android-studio" \
              "/opt/android-studio" "/Applications/Android Studio.app/Contents"; do
    for k in "$base/jbr/bin/keytool" "$base/jbr/bin/keytool.exe" \
             "$base/jbr/Contents/Home/bin/keytool"; do
      [ -f "$k" ] && { printf '%s' "$k"; return 0; }
    done
  done
  return 1
}

# ------------------------------------------------------------ signing setup ---
if [ ! -f "$PROPS" ]; then
  cyan "Setting up signing (first run only)"

  KEYTOOL="$(find_keytool)" || die \
"keytool not found. It ships with the JDK - install Android Studio, or set JAVA_HOME."

  if [ -f "$KEYSTORE" ]; then
    # keystore exists but we have no properties file: we need the password
    info "Found $KEYSTORE but no $PROPS."
    if [ -n "${KEYSTORE_PASSWORD:-}" ]; then
      PASS="$KEYSTORE_PASSWORD"
    else
      printf '    Keystore password: '
      read -r -s PASS
      printf '\n'
    fi
    [ -n "$PASS" ] || die "No password given."
  else
    PASS="${KEYSTORE_PASSWORD:-$(random_password)}"
    info "Creating upload key $KEYSTORE (valid ~27 years)"
    "$KEYTOOL" -genkeypair \
      -keystore "$KEYSTORE" -alias "$ALIAS" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -storepass "$PASS" -keypass "$PASS" \
      -dname "$DNAME" >/dev/null
    chmod 600 "$KEYSTORE" 2>/dev/null || true
    info "key created"
  fi

  umask 077
  cat > "$PROPS" <<PROPFILE
# Generated by build-release.sh. Gitignored - never commit this.
storeFile=$(native_path "$PWD/$KEYSTORE")
storePassword=$PASS
keyAlias=$ALIAS
keyPassword=$PASS
PROPFILE
  info "wrote $PROPS"

  printf '\n\033[33m'
  cat <<TXT
    ---------------------------------------------------------------
    BACK UP $KEYSTORE AND $PROPS, SOMEWHERE SAFE
    AND OFF THIS MACHINE.

    Google Play ties your listing to this key. Lose it and you can
    never publish an update to the same app - you'd have to start
    a new listing and every install would be orphaned.
    ---------------------------------------------------------------
TXT
  printf '\033[0m'
else
  info "Using existing $PROPS"
fi

# ------------------------------------------------------------------- build ---
[ "$WANT_AAB" = "1" ] && { cyan "Building signed AAB for Play"; ./build-apk.sh --bundle; }
[ "$WANT_APK" = "1" ] && { cyan "Building signed APK";          ./build-apk.sh --release; }

cyan "Release build finished"
[ "$WANT_AAB" = "1" ] && printf '    \033[32m%s\033[0m  upload this to Play\n'     "$SLUG-release.aab"
[ "$WANT_APK" = "1" ] && printf '    \033[32m%s\033[0m  install this on a phone\n' "$SLUG-release.apk"

cat <<TXT

    Play checklist is in BUILD.md. The short version:
      - privacy policy URL: ${PRIVACY_URL:-<set PRIVACY_URL in build.conf>}
      - Data safety: answer "no data collected" throughout
      - store listing must say pretend / entertainment, not a real scanner
TXT
